import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import ordersRouter from "./orders";
import customersRouter from "./customers";
import usersRouter from "./users";
import dashboardRouter from "./dashboard";
import settingsRouter from "./settings";
import reportsRouter from "./reports";
import printConfigRouter from "./print-config";
import printLogRouter from "./print-log";
import printersRouter from "./printers";
import printerSettingsRouter from "./printer-settings";
import hrRouter from "./hr";
import returnsRouter from "./returns";
import accountingRouter from "./accounting";
import branchesRouter from "./branches";
import suppliersRouter from "./suppliers";
import purchasesRouter from "./purchases";
import shiftsRouter from "./shifts";
import tablesRouter from "./tables";
import kdsRouter from "./kds";
import recipesRouter from "./recipes";
import expensesRouter from "./expenses";
import licensesRouter from "./licenses";
import auditRouter from "./audit";
import systemRouter from "./system";
import documentPrintSettingsRouter from "./document-print-settings";
import inventoryRouter from "./inventory";
import safesRouter from "./safes";
import onyxRouter from "./onyx";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(categoriesRouter);
router.use(productsRouter);
router.use(ordersRouter);
router.use(customersRouter);
router.use(usersRouter);
router.use(dashboardRouter);
router.use(settingsRouter);
router.use(reportsRouter);
router.use(printConfigRouter);
router.use(printLogRouter);
router.use(printersRouter);
router.use(printerSettingsRouter);
router.use(hrRouter);
router.use(returnsRouter);
router.use(accountingRouter);
router.use(branchesRouter);
router.use(suppliersRouter);
router.use(purchasesRouter);
router.use(shiftsRouter);
router.use(tablesRouter);
router.use(kdsRouter);
router.use(recipesRouter);
router.use(expensesRouter);
router.use(licensesRouter);
router.use(auditRouter);
router.use(systemRouter);
router.use(documentPrintSettingsRouter);
router.use(inventoryRouter);
router.use(safesRouter);
router.use(onyxRouter);

export default router;
